export const ACTION_TYPES = {
  STUDENTS_LISTING: "STUDENTS_LISTING",
  STUDENTS_DELETION: "STUDENTS_DELETION",
  STUDENTS_UPDATION: "STUDENTS_UPDATION",
  STUDENTS_GET_BY_ID: "STUDENTS_GET_BY_ID",
};
